### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by equationzhao** [WitchElaina/ustb-gym-backend#4]
![image](https://github.com/WitchElaina/ustb-gym-backend/assets/75521101/1d026677-5d4e-4ce0-b10c-122f618b6fa7)

空仓球是什么（

**Comment by WitchElaina** [comment]
![image](https://github.com/WitchElaina/ustb-gym-backend/assets/81346402/e6901e99-3670-41c5-bd68-491670b76019)
